#FROM ubuntu:focal
FROM cr.loongnix.cn/library/debian:buster-slim

#RUN sed -i "s/http:\/\/deb.debian.org\/debian/http:\/\/mirrors.ustc.edu.cn\/debian/" /etc/apt/sources.list.d/debian.sources \
#    && apt update

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y git \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ruby ruby-dev rubygems build-essential rpm \
    && gem install dotenv -v 2.8.1 \
    && gem install fpm -v 1.16.0 \
    && fpm --version

CMD /usr/local/bin/fpm
